{% set name = "dvclive" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dvclive-{{ version }}.tar.gz
  sha256: ca4538629f2cfde4c371adf6b03f660334bcef311d077185e7c9be38b7d314a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=6.3.1
  run:
    - dvc-render
    - ruamel.yaml >=0.17.11
    - python >=3.8

test:
  imports:
    - dvclive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://dvc.org/doc/dvclive
  summary: Metric logger for ML projects.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daavoo
    - efiop
    - shcheklein
